### ISSUE TITLE
'CameraCaptureARFoundation' could not be found

### ISSUE THREAD

**Issue by janla** [microsoft/MRLightingTools-Unity#3]
Hi,

i'm trying to use the the MR Lighting Tools in Unity 2018.3.7 with ARFoundation 1.5.0 preview 2 and get the following error message when trying to build for Android: 
`Assets/MixedRealityToolkit.LightingTools/LightCapture.cs(79,24): error CS0246: The type or namespace name 'CameraCaptureARFoundation' could not be found (are you missing a using directive or an assembly reference?)`

These are my build settings:
<img width="494" alt="Bildschirmfoto 2019-05-21 um 12 42 25" src="https://user-images.githubusercontent.com/3298139/58089792-f3c41b00-7bc5-11e9-9761-40531698007f.png">

Any idea what could be wrong?
Thanks in advance,
Jan

**Comment by mert-dev-acc** [comment]
You need to add `USE_ARFOUNDATION `to your Script Define symbols. But also some apis are depricated. So an update for ARFoundation 2.1 is needed.

**Comment by maluoi** [comment]
Should be resolved as of v0.1.2

**Comment by ossala** [comment]
Having this issue when trying to build for Android. Added ARFoundation but looks like it's been updated and they have removed the functions for try get image. Tried downgrading ARFoundation and it builds but the skybox just comes up black when on device.

**Comment by maluoi** [comment]
Heyas! What version of ARFoundation are you using?

I updated this for ARFoundation 2, and this may work with the 1.5 that's supposed to be equivalent to 2.x? But I'm not certain if this is available in Unity 2018.3, try with 2018.4. Their versioning has gotten a bit weird, and it's not documented all that well right now =/
